import { Exercise } from "@/types";

export const BUILTIN_EXERCISES: Exercise[] = [
  {
    id: "ex_bench_press",
    name: "Barbell Bench Press",
    targetMuscle: "Chest",
    secondaryMuscles: ["Shoulders", "Arms"],
    equipment: "Barbell",
    instructions: "Retract scapulae, touch lower sternum, press up over shoulders.",
    isCustom: false,
    isArchived: false,
  },
  {
    id: "ex_incline_db_press",
    name: "Incline Dumbbell Press",
    targetMuscle: "Chest",
    secondaryMuscles: ["Shoulders", "Arms"],
    equipment: "Dumbbell",
    instructions: "Set bench angle to 30 degrees. Control the eccentric descent.",
    isCustom: false,
    isArchived: false,
  },
  {
    id: "ex_barbell_squat",
    name: "Barbell Squat",
    targetMuscle: "Legs",
    secondaryMuscles: ["Core"],
    equipment: "Barbell",
    instructions: "Brace core, descend until hip crease is below knee level.",
    isCustom: false,
    isArchived: false,
  },
  {
    id: "ex_conventional_deadlift",
    name: "Conventional Deadlift",
    targetMuscle: "Back",
    secondaryMuscles: ["Legs", "Core"],
    equipment: "Barbell",
    instructions: "Take slack out of the bar, lock hips and knees simultaneously.",
    isCustom: false,
    isArchived: false,
  },
  {
    id: "ex_overhead_press",
    name: "Standing Overhead Press",
    targetMuscle: "Shoulders",
    secondaryMuscles: ["Arms", "Core"],
    equipment: "Barbell",
    instructions: "Press directly overhead while keeping glutes locked.",
    isCustom: false,
    isArchived: false,
  },
  {
    id: "ex_lat_pulldown",
    name: "Lat Pulldown",
    targetMuscle: "Back",
    secondaryMuscles: ["Arms"],
    equipment: "Cable",
    instructions: "Pull smoothly to the upper collarbone, driving elbows downward.",
    isCustom: false,
    isArchived: false,
  },
  {
    id: "ex_romanian_deadlift",
    name: "Romanian Deadlift",
    targetMuscle: "Legs",
    secondaryMuscles: ["Back"],
    equipment: "Barbell",
    instructions: "Hinge backwards at the hips with knees fixed in a slight bend.",
    isCustom: false,
    isArchived: false,
  },
  {
    id: "ex_lateral_raise",
    name: "Dumbbell Lateral Raise",
    targetMuscle: "Shoulders",
    equipment: "Dumbbell",
    instructions: "Raise arms slightly forward in the scapular plane with palms downward.",
    isCustom: false,
    isArchived: false,
  },
  {
    id: "ex_tricep_pushdown",
    name: "Tricep Rope Pushdown",
    targetMuscle: "Arms",
    equipment: "Cable",
    instructions: "Pin elbows beside ribs, flared outwards at lockout.",
    isCustom: false,
    isArchived: false,
  },
  {
    id: "ex_barbell_curl",
    name: "Barbell Bicep Curl",
    targetMuscle: "Arms",
    equipment: "Barbell",
    instructions: "Supinate and curl without using torso momentum.",
    isCustom: false,
    isArchived: false,
  },
];